### DISCUSSION TITLE
Synthtiger: korean dataset for doctr training

### DISCUSSION THREAD

**Discussion by khawar-islam** [mindee/doctr#1098] [General]
Hi @felixdittrich92 , thank you for you suggestion. After your suggestion, I have worked on `https://github.com/clovaai/synthtiger` repo and generate a new korean synthetic dataset. I have attached the .zip for your confirmation then i will be able to generate full 5 Million images dataset. I have changed some paramters for doctr training, please have a look on configuration and .zip file

While preparing training data, we do not need `masks` and `coords.txt` information. **Am i right?**
**Can i generate the vertical and multi line images for doctr training? Is that OK** 

```
vertical: false
quality: [60, 95]
visibility_check: true

midground: 0.25
midground_offset:
  percents: [[-0.5, 0.5], [-0.5, 0.5]]
foreground_mask_pad: 5

corpus:
  weights: [1, 0]
  args:
    # length augmentable corpus
    - paths: [resources/corpus/ko.txt]
      weights: [1]
      min_length: 1
      max_length: 10
      textcase: [lower, upper, capitalize]
      augmentation: 0.1
      augmentation_length: [1, 10]
    # char augmentable corpus
    - paths: []
      weights: []
      min_length: 1
      max_length: 10
      textcase: [lower, upper, capitalize]
      augmentation: 0
      augmentation_charset: resources/charset/alphanum_special.txt

font:
  paths: [resources/font]
  weights: [1]
  size: [40, 80]
  bold: 0.5

texture:
  prob: 0.5
  args:
    paths: [resources/image]
    weights: [1]
    alpha: [0, 1]
    grayscale: 0
    crop: 1

colormap2:
  paths: [resources/colormap/iiit5k_gray.txt]
  weights: [1]
  k: 2
  alpha: [1, 1]
  colorize: 1

colormap3:
  paths: [resources/colormap/iiit5k_gray.txt]
  weights: [1]
  k: 3
  alpha: [1, 1]
  colorize: 1

color:
  gray: [0, 255]
  alpha: [1, 1]
  colorize: 1

shape:
  prob: 1
  args:
    weights: [1, 1]
    args:
      # elastic distortion
      - alpha: [15, 20]
        sigma: [4, 12]
      # elastic distortion
      - alpha: [0, 2]
        sigma: [0, 0.6]

layout:
  weights: [4, 1]
  args:
    # flow layout
    - space: [-2, 5]
      line_align: [middle]
    # curve layout
    - curve: [20, 40]
      space: [-2, 5]
      convex: 0.5
      upward: 0.5

style:
  prob: 0.25
  args:
    weights: [1, 2, 2]
    args:
      # text border
      - size: [1, 12]
        alpha: [1, 1]
        grayscale: 0
      # text shadow
      - distance: [1, 6]
        angle: [0, 360]
        alpha: [0.3, 0.7]
        grayscale: 0
      # text extrusion
      - length: [1, 12]
        angle: [0, 360]
        alpha: [1, 1]
        grayscale: 0

transform:
  prob: 1
  args:
    weights: [1, 1, 1, 1, 1, 1, 2]
    args:
      # perspective x
      - percents: [[0.5, 1], [1, 1]]
        aligns: [[0, 0], [0, 0]]
      # perspective y
      - percents: [[1, 1], [0.5, 1]]
        aligns: [[0, 0], [0, 0]]
      # trapezoidate x
      - weights: [1, 0, 1, 0]
        percent: [0.75, 1]
        align: [-1, 1]
      # trapezoidate y
      - weights: [0, 1, 0, 1]
        percent: [0.5, 1]
        align: [-1, 1]
      # skew x
      - weights: [1, 0]
        angle: [0, 30]
        ccw: 0.5
      # skew y
      - weights: [0, 1]
        angle: [0, 10]
        ccw: 0.5
      # rotate
      - angle: [0, 10]
        ccw: 0.5

pad:
  prob: 1
  args:
    pxs: [[0, 10], [0, 10], [0, 10], [0, 10]]

postprocess:
  args:
    # gaussian noise
    - prob: 1
      args:
        scale: [4, 8]
        per_channel: 0
    # gaussian blur
    - prob: 0.9
      args:
        sigma: [0, 2]
    # resample
    - prob: 0.1
      args:
        size: [0.4, 0.4]
    # median blur
    - prob: 1
      args:
        k: [1, 1]
```

[results.zip](https://github.com/mindee/doctr/files/9797487/results.zip)
